### ISSUE TITLE
Ego4D Annotation

### ISSUE THREAD

**Issue by huaihailv** [Annusha/xmic#1]
I've searched for the following files in both xmic code base and Ego4D, and cannot obtain a accurate answer: 

1. mappping_verb.txt
2. mappping_noun.txt
3. fho_actions_actionidx_verb_noun.txt

And the script file parse_ego4d_json.py is missing also. Could you give a more detailed guide please if it's possible.

Thanks!

**Comment by Andrez092** [comment]
download
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by Annusha** [comment]
To create mappings you can use the script:
[ego4d_create_label_mappings.py](https://github.com/Annusha/xmic/blob/main/utils/ego4d_create_label_mappings.py)
change manually "mapping_label" from verb to noun to create both

fho_actions_actionidx_verb_noun - it's a file for actions, you can create it by combining verbs and nouns and assigning a unique id for the pair. It is not necessary to follow any specific order. Moreover, as far as I remember, in the end, I do not use action labels to report any results.
Feel free to just comment out the code that corresponds to action labels.

parse_ego4d_json.py file is just legacy from the original ego4d code that I was using as a reference:
[ptv_dataset_helper.py](https://github.com/EGO4D/forecasting/blob/38d1931b543decab420abc991577e30a5b6ccfc7/ego4d_forecasting/datasets/ptv_dataset_helper.py#L356)
you do not need this file

I hope it helps!

**Comment by avijit9** [comment]
Hi @Annusha , Do you also have the similar python code for processing the Epic-Kitchens dataset?
