### ISSUE TITLE
'trainers' folder seems don't have 'imagenet_templates' 

### ISSUE THREAD

**Issue by mantou-cloud** [Annusha/xmic#3]
Line 11 of 'trainers.zsclip.py'-------from .imagenet_templates import IMAGENET_TEMPLATES, IMAGENET_TEMPLATES_SELECT, it seems that there are no 'imagenet_templates' file. I'd like to ask where i can find it? Thanks for your help!

**Comment by Annusha** [comment]
I've added the file. Sorry for the inconvenience! 
If sth else basic is missing, you can check https://github.com/muzairkhattak/multimodal-prompt-learning/tree/main code as I was building the framework upon this one. 
I'll try to make the code fully runnable within the next weeks

**Comment by mantou-cloud** [comment]
I've seen the file, and I'll follow the links you provided to check other files. Thanks for your work on the code!
